/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.polidea.gajowy.laying_parquet.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1836634319637965847L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Record\",\"namespace\":\"com.polidea.gajowy.laying_parquet.avro\",\"fields\":[{\"name\":\"row\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence row;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Record() {}

  /**
   * All-args constructor.
   * @param row The new value for row
   */
  public Record(java.lang.CharSequence row) {
    this.row = row;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return row;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: row = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'row' field.
   * @return The value of the 'row' field.
   */
  public java.lang.CharSequence getRow() {
    return row;
  }

  /**
   * Sets the value of the 'row' field.
   * @param value the value to set.
   */
  public void setRow(java.lang.CharSequence value) {
    this.row = value;
  }

  /**
   * Creates a new Record RecordBuilder.
   * @return A new Record RecordBuilder
   */
  public static com.polidea.gajowy.laying_parquet.avro.Record.Builder newBuilder() {
    return new com.polidea.gajowy.laying_parquet.avro.Record.Builder();
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Record RecordBuilder
   */
  public static com.polidea.gajowy.laying_parquet.avro.Record.Builder newBuilder(com.polidea.gajowy.laying_parquet.avro.Record.Builder other) {
    return new com.polidea.gajowy.laying_parquet.avro.Record.Builder(other);
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Record instance.
   * @param other The existing instance to copy.
   * @return A new Record RecordBuilder
   */
  public static com.polidea.gajowy.laying_parquet.avro.Record.Builder newBuilder(com.polidea.gajowy.laying_parquet.avro.Record other) {
    return new com.polidea.gajowy.laying_parquet.avro.Record.Builder(other);
  }

  /**
   * RecordBuilder for Record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Record>
    implements org.apache.avro.data.RecordBuilder<Record> {

    private java.lang.CharSequence row;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.polidea.gajowy.laying_parquet.avro.Record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.row)) {
        this.row = data().deepCopy(fields()[0].schema(), other.row);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Record instance
     * @param other The existing instance to copy.
     */
    private Builder(com.polidea.gajowy.laying_parquet.avro.Record other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.row)) {
        this.row = data().deepCopy(fields()[0].schema(), other.row);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'row' field.
      * @return The value.
      */
    public java.lang.CharSequence getRow() {
      return row;
    }

    /**
      * Sets the value of the 'row' field.
      * @param value The value of 'row'.
      * @return This builder.
      */
    public com.polidea.gajowy.laying_parquet.avro.Record.Builder setRow(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.row = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'row' field has been set.
      * @return True if the 'row' field has been set, false otherwise.
      */
    public boolean hasRow() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'row' field.
      * @return This builder.
      */
    public com.polidea.gajowy.laying_parquet.avro.Record.Builder clearRow() {
      row = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Record build() {
      try {
        Record record = new Record();
        record.row = fieldSetFlags()[0] ? this.row : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
